import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const emails = [
  "t.abi13@yahoo.com",
  "texaskickboxing@gmail.com",
  "changstein3@gmail.com",
  "ella3118@sbcglobal.net",
  "mando.g369@gmail.com",
  "maggie@charlotte.com.mx",
  "arondhuchins@gmail.com",
  "daubers.pups85@icloud.com",
  "joe11023@cloud.com",
  "beatriztamayo@yahoo.com",
  "brud200@gmail.com",
  "benjaminsaucedo2@gmail.com",
  "adelinks2000@yahoo.com",
  "batuner2019@gmail.com",
  "k-nakol@yahoo.com",
  "tolmultiservice@gmail.com",
  "cedeag@hotmail.com",
  "88ragnarok@gmail.com",
  "charles.grey@att.net",
  "cjpivonka@comcast.net",
  "chris.pricejk2019@gmail.com",
  "gannon_cj@yahoo.com",
  "alianzarebellc@gmail.com",
  "enblackshear@gmail.com",
  "crukcontruction@gmail.com",
  "velazquez77091@hotmail.com",
  "d.boehm4106@gmail.com",
  "orthojunkie@gmail.com",
  "attorney.dave@yahoo.com",
  "shih_kang@yahoo.com",
  "fatemah@dhtexas.org",
  "garcia8367@att.net",
  "dmalinowski@slb.com",
  "morrisondm@gmail.com",
  "duy.luong@yahoo.com",
  "berguer5843@sbcglobal.net",
  "eifer731@gmail.com",
  "eduard.g.bustos@gmail.com",
  "eduriermarquez@gmail.com",
  "emaniehendo@gmail.com",
  "emmanuel77493@gmail.com",
  "elejew8@gmail.com",
  "estraveler@aol.com",
  "epanesso74@gmail.com",
  "elfoster4@hotmail.com",
  "esthert.dunne@gmail.com",
  "evadiez64@gmail.com",
  "flaviah@me.com",
  "frenchys7955@gmail.com",
  "igaby1927@gmail.com",
  "glchaoin@outlook.com",
  "g.jonesnov03@gmail.com",
  "glrke65@gmail.com",
  "greg.tran@sbcglobal.net",
  "gregorybekker.gb@gmail.com",
  "gunther.gronins@gmail.com",
  "evamex3@yahoo.com",
  "hadja3@yahoo.com",
  "mayhews1115@gmail.com",
  "adefashe@hotmail.com",
  "meilyn.corona@yahoo.com",
  "helenjack426@gmail.com",
  "helenparker@cct.net",
  "hank0007@aol.com",
  "derick52@hotmail.com",
  "icontet8@gmail.com",
  "nieser@sbcglobal.net",
  "jckbrr.tt@gmail.com",
  "jroddyob@gmail.com",
  "nathomas580@gmail.com",
  "jayhousholder@gmail.com",
  "yoaluz@yahoo.com",
  "jlgowen@yahoo.com",
  "markus@earl-and-markus.com",
  "jpolson@yahoo.com",
  "kconstanten@hotmail.com",
  "kayleezittrer@gmail.com",
  "yglesias2004@yahoo.com",
  "guzmancito71@hotmail.com",
  "leland.a.cannon@gmail.com",
  "riverstomdriving@sbc.global.net",
  "lpaneso@hotmail.com",
  "linlinheahn@yahoo.com",
  "lise@texasreg.com",
  "sv442L@yahoo.com",
  "ld_texas@yahoo.com",
  "lnmercado@amcast.net",
  "enasonso1988@gmail.com",
  "ldmhtx@gmail.com",
  "tahashujauddin@yahoo.com",
  "safresa2103@hotmail.com",
  "gonzalezlupe51@yahoo.com",
  "mjorgeortega@gmail.com",
  "markccddsmbao@yahoo.com",
  "mark77379@yahoo.com",
  "mpeek76@gmail.com",
  "mrmichaelbednar@gmail.com",
  "mikey.57255@gmail.com",
  "mmancia@aol.com",
  "mdolan.tx@gmail.com",
  "amakaumachia@gmail.com",
  "netocouso@yahoo.com",
  "badaopemipo@gmail.com",
  "vsenp8@gmail.com",
  "patriciambermudez@gmail.com",
  "aisackos@yahoo.com",
  "bellowphillman@gmail.com",
  "nb281171@yahoo.com",
  "ramonfgarcia@yahoo.com",
  "rlacazia@yahoo.com",
  "raulmchdo@yahoo.com",
  "rbenson09.rd@gmail.com",
  "raydele90@gmail.com",
  "smrk2022@outlook.com",
  "rayologistics@gmail.com",
  "reginaperkins@gmail.com",
  "rjstaffeld@yahoo.com",
  "rdruce@ieee.org",
  "rcj2012@icloud.com",
  "robertahum1992@gmail.com",
  "dale.labeau@gmail.com",
  "s.inclan88c@yahoo.com",
  "sandrammvalencia@gmail.com",
  "sharondwhetstone@gmail.com",
  "bellshawn70@yahoo.com",
  "miss_nu2@yahoo.com",
  "sovonthou@yahoo.com",
  "staciyclark@gmail.com",
  "sunny.timbalia@gmail.com",
  "tarig.osman007@gmail.com",
  "jerome.rhodes55@yahoo.com",
  "ttran1188@gmail.com",
  "mrstv@att.net",
  "timothy.villanueva@att.net",
  "topefolarin@gmail.com",
  "velmashockley@prodigy.net",
  "yolanager@icloud.com",
  "villedayoni78@gmail.com",
  "allen.orum@gmail.com",
  "cicumarin@yahoo.com",
  "corbincneilson@gmail.com",
  "danielle_brown86@yahoo.com",
  "dhg5737@gmail.com",
  "fabpluquet@gmail.com",
  "hughlsp@gmail.com",
  "joec@smartsubseaus.com",
  "jthomas@constantsecurity.net",
  "keithcordero@sbcglobal.net",
  "lashandamaule@hotmail.com",
  "matt_kessinger@yahoo.com",
  "melissawong365@gmail.com",
  "nhoffman1970@gmail.com",
  "olatubosun.funmi@yahoo.com",
  "roberca31@gmail.com",
  "rskutca@sbcglobal.net",
  "sschiba786@gmail.com",
  "starr219@gmail.com",
  "shailapochi@gmail.com",
  "dania.lopez@yahoo.com",
  "ridgejoh30ml@gmail.com",
  "milmeg@aol.com",
  "ndnguyen@outlook.com",
  "stevenflowers@yahoo.com",
  "djrice@gmail.com",
  "jadlen@live.com",
  "alan_in_wa@yahoo.com",
  "mflores4life@aol.com",
  "sanhouty@gmail.com",
  "mangal.mirwais14060@gmail.com",
  "ryanroeske@yahoo.com",
  "pbrown5353@yahoo.com",
  "jfeagin69@gmail.com",
  "reynoldsconnor47@gmail.com",
  "angus@heavyequipmentguide.com",
  "condefa@hotmail.com",
  "johnferruzzo87@gmail.com",
  "jmolexen@yahoo.com",
  "g-castillos@live.com",
  "kevinplyons@icloud.com",
  "cposell@simplystatedhouston.com",
  "fadiakdhelias@gmail.com",
  "adonayrscuba@gmail.com",
  "meganholtgrave@gmail.com",
  "davidholtgrave94@gmail.com",
  "drgizersky@gmail.com",
  "mbakery@memorialbakery.com",
  "arizreynolds@att.com",
  "sandragarcia0103@gmail.com",
  "waldrep.tom@att.net",
  "annewaldrep@att.net",
  "queenbea27@sbcglobal.net",
  "gregv133@yahoo.com",
  "underbrinkjan@gmail.com",
  "teamheitman@hotmail.com",
  "britgetclytn@yahoo.com",
  "garmaly@att.net",
  "tndunn13@gmail.com",
  "joecambell145@gmail.com",
  "pablorubio2123@gmail.com",
  "shawn.fro@icloud.com",
  "mjsvr@att.net",
  "michaeldavidblanco@gmail.com",
  "bradc@morrellmasonry.com",
  "elita.musliu@yahoo.com",
  "tristatetaxidermy@comcast.net",
  "travisself07@yahoo.com",
  "butthyder@gmail.com",
  "ed@theheritagemeyerland.com",
  "jh322278@yahoo.com",
  "txrealtor@comcast.net",
  "planit3x@gmail.com",
  "amymaxwell9@gmail.com",
  "shenshong0125@gmail.com",
  "brian.lardi@hotmail.com",
  "esther.dunn@gmail.com",
  "david@lukahenergy.com",
  "shanbay@att.net",
  "bennyzhuang09@gmail.com",
  "kaasproperties25@gmail.com",
  "fatemac@dhtexas.org",
  "bbcamarillo@gmail.com",
  "rdcarmi@gmail.com",
  "edgarvillafane@gmail.com",
  "ms.khong@outlook.com",
  "property.hun@ahmadiyya.us",
  "vassolo@gmail.com",
  "dbankstxii@aol.com",
  "fsstewart1@gmail.com",
  "rosalie.schwarz5@gmail.com",
  "allison@alandaughtrylaw.com",
  "cisneroscustomcarpentry@yahoo.com",
  "tonis@svllc.net",
  "grosu.dan@gmail.com",
  "deesworld@gmail.com",
  "vpgarza0501@gmail.com",
  "gisgurutx@gmail.com",
  "vesseygiles@gmail.com",
  "gilbert@gbgarza.com",
  "joey@thedalyround.com",
  "raymondweems1@gmail.com",
  "orum.michael@gmail.com",
  "jcryquilt@gmail.com",
  "maxmmotta@gmail.com",
  "htruffintejeda@gmail.com",
  "kendra.walker@compass.com",
  "emilieramos@att.net",
  "johnnyraia2_@hotmail.com",
  "rigos1411@gmail.com",
  "azgcm@outlook.com",
  "jpkoke@gmail.com",
  "larrydoral@gmail.com",
  "shishabraids@yahoo.com",
  "brightbholdings@yahoo.com",
  "dulcemduarte@icloud.com",
  "jrodriguez@sentriforce.com",
  "josec8619@gmail.com",
  "latashadorsey72304@yahoo.com",
  "stereomann74@gmail.com",
  "silverbackcollision@live.com",
  "gefons@fonscor.com",
  "dovesics@gmail.com",
  "radducci@bldrschoice.com",
  "info@sqsoccer.com",
  "jhonnyraia2@toxicologyassociates.com",
  "joygregory@sbcglobal.net",
  "patriciabermudez@gmail.com",
  "a51craigster@sbcglobal.net",
  "dberger@ipipes.com",
  "lagiraldillabakery@gmail.com",
  "markecddsmba@yahoo.com",
  "jonnette.finly@dtps.state.tx.us",
  "mybulkaccount@yahoo.com",
  "dahri@att.net",
  "ammie32@sbcglobal.net",
  "albert.mesa@att.net",
  "iconteh8@gmail.com",
  "gary.burkinshaw@me.com",
  "gunilla.abbott@gmail.com",
  "arielfigeroa883@gmail.com",
  "tom.brewer@danerealtytexas.com",
  "sarahaggreh@yahoo.com",
  "jlgrayado@gmail.com",
  "clhernz59@yahoo.com",
  "kumar128@gmail.com",
  "safresa2013@hotmail.com",
  "katz4now@hotmail.com",
  "whbronw@hotmail.com",
  "nellycs28@yahoo.com",
  "kevingardener2014@gmail.com",
  "j23nichola@hotmail.com",
  "amakaumadia@gmail.com",
  "nermeena.kamal@gmail.com",
  "aida.sanches@hotmail.com",
  "khutalechetan@gmail.com",
  "duartenayiby@gmail.com",
  "billk@highstreetllc.com",
  "tdgood111@yahoo.com",
  "Jerome.rhodes55@yahoo.com",
  "robinlhale@peoplepc.com",
  "deswilli711@gmail.com",
  "sealadetio@gmail.com",
  "jljones1948@att.net",
  "vidiliaz@yahoo.com",
  "billy@wwtshou.com",
  "obj.g@att.net",
  "zarrarahmad@gmail.com",
  "brad.maddux@yahoo.com",
  "luciobazan@hotmail.com",
  "twryc@comcast.net",
  "chris6401@att.net",
  "tarig.osmano07@gmail.com",
  "hparedes97@gmail.com",
  "levuh@yahoo.com",
  "exkloosiuz@yahoo.com",
  "dania.lopez43@yahoo.com",
  "mpozos87@gmail.com",
  "villedayoni78@gmaol.com",
  "berniemccoyjr@hotmail.com",
  "custodiocastro1@gmail.com",
  "rsolchal@jrbengineering.com",
  "adestherlog@gmail.com",
  "hudnallk@yahoo.com",
  "marcojec@hotmail.com",
  "c_stroy26@yahoo.com",
  "yudithpedraza@gmail.com",
  "carmenlozano21@gmail.com",
  "weeds1957sparkle@yahoo.com",
  "bigbendsky@gmail.com",
  "santihcalifornia@aol.com",
  "cprokofieff@gmail.com",
  "dan@flangeprotection.com",
  "gunther.groning@gmail.com",
  "fjones@endeavordevel.com",
  "elizabethbonnie50@gmail.com",
  "kpoirrier@aol.com",
  "terancegartica@yahoo.com",
  "mourningcar@gmail.com",
  "paulgerke53@gmail.com",
  "melissamcclain14@aol.com",
  "jpol50@yahoo.com",
  "henurse2@hotmail.com",
  "odumbj@gmail.com",
  "chitra.shukla@att.net",
  "twalls@superbag.com",
  "jameslm95@yahoo.com",
  "joel2006ana@yahoo.com",
  "vegajoanna07@gmail.com",
  "narilynriley@yahoo.com",
  "nahly730@gmail.com",
  "dreasanchez@yahoo.com",
  "vernnonhuggans@gmail.com",
  "lorev767@gmail.com",
  "roxanavelez95@gmail.com",
  "lisa.a.degraff@gmail.com",
  "ykchod@gmail.com",
  "andrewtaulton@hotmail.com",
  "jujurn10@comcast.net",
  "jaypee1128@gmail.com",
  "raidele90@gmail.com",
  "baturner2019@gmail.com",
  "charles.gray@att.net",
  "helenparker@att.net",
  "gillispiekyle@yahoo.com",
  "lisa@texasreg.com",
  "renaissancerenovationllc@gmail.com",
  "tosinodetola@hotmail.com",
  "orlandac36@gmail.com",
  "blueseas@gmail.com",
  "Jacob.a.sneed@gmail.com",
  "nathomas80@yahoo.com",
  "mikedelacruz50@yahoo.com",
  "jmata_1953@yahoo.com",
  "asantiago1027@yahoo.com",
  "jessica@dtlogos.com",
  "reginaperkins@sbcglobal.net",
  "bmstevens4@gmail.com",
  "rb08182013@gmail.com",
  "yglesias1996@icloud.com",
  "s.inclan88@yahoo.com",
  "morrisondn@gmail.com",
  "donaldrrawls@yahoo.com",
  "luv2jam85@gmail.com",
  "emmanuel177493@gmail.com",
  "catherinemontz@yahoo.com",
  "riverstonedriving@sbcglobal.net",
  "xavier@as.hn",
  "jhonnatanrubio@hotmail.com",
  "glrice65@gmail.com",
  "cruckconstruction@gmail.com",
  "mcmarlison@aol.com",
  "glgowen@yahoo.com",
  "pedromanuelantuna@gmail.com",
  "jcaraujo@sbcglobal.net",
  "edward.g.bustos@gmail.com",
  "ella3118@hotmail.com",
  "Jennifer.master@sagemontchurch.org",
  "glchapin@outlook.com",
  "cora.straker@yahoo.com",
  "rayologistic@gmail.com",
  "Jolivet.lilliam@gmail.com",
  "ctownsend1047@gmail.com",
  "lemasupply@hotmail.com",
  "zachary@leveledconcrete.com",
  "gonzalezlupe@yahoo.com",
  "aisack05@yahoo.com",
  "steflebrun@doffing.net",
  "lidialva@yahoo.com",
  "drc@trueimageortho.com",
  "n_nakol@yahoo.com",
  "tysonlanch@gmail.com",
  "gbluescreen@gmail.com",
  "ernestonap@gmail.com",
  "roberto.dalton@sls.com",
  "bmcmillen961@gmail.com",
  "chamdal6@sbcglobal.net",
  "cjsingh727@gmail.com",
  "netocouso@yahoo.es",
  "sam.banda@integrallift.com",
  "vrangel425@gmail.com",
  "ammarlazo@yahoo.com",
  "landmark672002@yahoo.com",
  "hnicole0711@yahoo.com",
  "cobincnielson@gmail.com",
  "cnblackshear@gmail.com",
  "prettypawspetspallc@gmail.com",
  "barretdl85@gmail.com",
  "aronhutchins@gmail.com",
  "barret@saihouston.com",
  "ymmlumm@gmail.com",
  "erodez00@hotmail.com",
  "cookiell1355@yahoo.com",
  "marcusdspencer@hotmail.com",
  "rodnaisycherilson@yahoo.com",
  "topefolarin@hotmail.com",
  "eduviermarquez@gmail.com",
  "hank007@aol.com",
  "kblestarge@gmail.com",
  "lgaby1927@gmail.com",
  "captainstevewebber@gmail.com",
  "bernshausen@gmail.com",
  "jameson@gmail.com",
  "jilliancumo@sbcglobal.net",
  "olga.bonjour@yahoo.com",
  "nuella246@gmail.com",
  "sales@citywidepatios.com",
  "elizabethbarberena@live.com",
  "davidckurtz06@gmail.com",
  "zelaya_francis@yahoo.com",
  "jroddy06@gmail.com",
];

async function main() {
  console.log("🌱 Starting seed...");

  // Get unique emails (remove duplicates)
  const uniqueEmails = [...new Set(emails)];

  console.log(`📧 Total unique emails: ${uniqueEmails.length}`);

  let created = 0;
  let skipped = 0;
  let errors = 0;

  for (const email of uniqueEmails) {
    try {
      // Check if email already exists
      const existing = await prisma.contactEmail.findUnique({
        where: { email },
      });

      if (existing) {
        console.log(`⏭️  Skipped (already exists): ${email}`);
        skipped++;
        continue;
      }

      // Extract name from email (before @)
      const name = email.split("@")[0].replace(/[._-]/g, " ");
      const capitalizedName = name
        .split(" ")
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(" ");

      // Create contact with email
      await prisma.contact.create({
        data: {
          name: capitalizedName,
          marketingConsent: true, // All have consent for marketing
          emails: {
            create: {
              email: email.toLowerCase(),
            },
          },
        },
      });

      console.log(`✅ Created: ${email} (${capitalizedName})`);
      created++;
    } catch (error) {
      console.error(`❌ Error creating ${email}:`, error);
      errors++;
    }
  }

  console.log("\n📊 Seed Summary:");
  console.log(`✅ Created: ${created}`);
  console.log(`⏭️  Skipped: ${skipped}`);
  console.log(`❌ Errors: ${errors}`);
  console.log(`📧 Total: ${uniqueEmails.length}`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
